alertBasicAuth:
  username: "![Z36buQMaynU5SHqoYs607g==]"
  password: "![Z36buQMaynU5SHqoYs607g==]"
  
wellsfargo-pgp:
  passphrase: "![Yx+lPSeiHIrmndjHMnEy0g==]"
  
sftp:
  password: "![hHT3N0u3ZOQXN1Cb+nwawRcrQswIutLf+OjpA35tqQU=]"